# Generated by Django 4.2 on 2023-05-14 22:30

from django.db import migrations
#from django.contrib.auth.models import User,Group,Permission

def create_groups(apps, schema_migration):
    User = apps.get_model('utilisateurs', 'User')
    Group = apps.get_model('utilisateurs', 'Group')
    Permission = apps.get_model('utilisateurs', 'Permission')

    ajouter = Permission.objects.get(codename = 'ajouter')
    modifier = Permission.objects.get(codename = 'modifier')
    supprimer = Permission.objects.get(codename = 'supprimer')
    afficher = Permission.objects.get(codename = 'afficher')

    preparateur_permissions = [
        ajouter,
        modifier,
        supprimer,
        afficher
    ]
    preparateurs = Group(name = 'preparateurs')
    preparateurs.save()
    preparateurs.permissions.set(preparateur_permissions)

    vendeurs = Group(name='vendeurs')
    vendeurs.save()
    vendeurs.permissions.add(ajouter,afficher)

    for user in User.objects.all():
        if user.role == 'PREPARATEURS':
            preparateurs.user_set.add(user)
        if user.role == 'VENDEURS':
            vendeurs.user_set.add(user)
class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
